services:
  symfony:
    build: .
    container_name: symfony
    ports:
      - "8080:80"
    volumes:
    - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d symfony"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: