# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true 
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: doctrine.event_listener, event: 'prePersist' }
            - { name: doctrine.event_listener, event: 'preUpdate' }
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }
    App\Domain\Event\Article\ArticleEventListener:
        tags:
            - { name: doctrine.orm.entity_listener, entity: App\Domain\Entity\Article\Article, event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: App\Domain\Entity\Article\Article, event: preUpdate }
        arguments:
            $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Domain/{Entity,Exception,RepositoryFilter,ValueObject}'
            - '../src/DependencyInjection/'
    App\Domain\Repository\Article\ArticleRepositoryInterface: '@App\Infrastructure\Persistence\Doctrine\Repository\Article\ArticleRepository'
